apiVersion: v1
kind: List  
metadata:
  name: armada-storage-microservice
  namespace: armada
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        openshift.io/cluster-monitoring: "true"
      name: openshift-storage
    spec: {}
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        openshift.io/cluster-monitoring: "true"
      name: local-storage
    spec: {}
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: openshift-storage-operatorgroup
      namespace: openshift-storage
    spec:
      targetNamespaces:
      - openshift-storage
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: local-storage-operatorgroup
      namespace: local-storage
    spec:
      targetNamespaces:
      - local-storage
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ocs-subscription
      namespace: openshift-storage
    spec:
      channel: stable-4.4
      name: ocs-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: local-storage-operator
      namespace: local-storage
    spec:
      channel: "4.4"
      name: local-storage-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  - apiVersion: local.storage.openshift.io/v1
    kind: LocalVolume
    metadata:
      name: local-block
      namespace: local-storage
    spec:
      nodeSelector:
        nodeSelectorTerms:
        - matchExpressions:
            - key: cluster.ocs.openshift.io/openshift-storage
              operator: In
              values:
              - ""
      storageClassDevices:
        - storageClassName: localblock
          volumeMode: Block
          devicePaths:
            - "{{{ item }}}"
  - apiVersion: ocs.openshift.io/v1
    kind: StorageCluster
    metadata:
      name: "{{ cluster-name }}"
      namespace: openshift-storage
    spec:
      manageNodes: false
      monPVCTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "{{ mon-storage-size }}" # 20Gi
          storageClassName: "{{ mon-storage-class }}" # ibmc-block-gold
          volumeMode: Filesystem
      storageDeviceSets:
      - count: 1
        dataPVCTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: "{{ osd-storage-size }}" #1
            storageClassName: "{{ osd-storage-class }}" #locakblock
            volumeMode: Block
        name: ocs-deviceset
        placement: {}
        portable: false
        replica: 3
        resources: {}
