apiVersion: v1
kind: List
metadata:
  name: ibm-openshift-container-storage
  namespace: kube-system
  #labels:
  #    deploy.razee.io/Reconcile: false
items:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      annotations:
        controller-gen.kubebuilder.io/version: v0.3.0
      name: ocsclusters.ocs.ibm.io
    spec:
      group: ocs.ibm.io
      names:
        kind: OcsCluster
        listKind: OcsClusterList
        plural: ocsclusters
        singular: ocscluster
      scope: Cluster
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            description: OcsCluster is the Schema for the ocsclusters API
            properties:
              apiVersion:
                description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                type: string
              kind:
                description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                type: string
              metadata:
                type: object
              spec:
                description: OcsClusterSpec defines the desired state of OcsCluster
                properties:
                  billingType:
                    default: hourly
                    enum:
                    - hourly
                    - monthly
                    type: string
                  ibmCosAccessKey:
                    type: string
                  ibmCosSecretKey:
                    type: string
                  monStorageClassName:
                    type: string
                  monDevicePaths:
                    items:
                      type: string
                    type: array
                  monSize:
                    type: string
                  numOfOsd:
                    default: 1
                    type: integer
                  ocsUpgrade:
                    default: false
                    type: boolean
                  osdStorageClassName:
                    type: string
                  osdDevicePaths:
                    items:
                      type: string
                    type: array
                  osdSize:
                    type: string
                  workerNodes:
                    items:
                      type: string
                    type: array
                required:
                - monSize
                - monStorageClassName
                - osdSize
                - osdStorageClassName
                type: object
              status:
                description: OcsClusterStatus defines the observed state of OcsCluster
                properties:
                  storageClusterStatus:
                    description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "make" to regenerate code after modifying this file'
                    type: string
                type: object
            type: object
        served: true
        storage: true
        subresources:
          status: {}
    status:
      acceptedNames:
        kind: ""
        plural: ""
      conditions: []
      storedVersions: []
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
      name: ibm-ocs-operator-leader-election-role
      namespace: kube-system
    rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - ""
      resources:
      - configmaps/status
      verbs:
      - get
      - update
      - patch
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - create
      - patch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
      name: ibm-ocs-operator-manager-role
    rules:
    - apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - persistentvolumes
      verbs:
      - deletecollection
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - create
      - delete
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - get
      - list
      - patch
      - watch
    - apiGroups:
      - local.storage.openshift.io
      resources:
      - localvolumes
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ocs.ibm.io
      resources:
      - ocsclusters
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ocs.ibm.io
      resources:
      - ocsclusters/status
      verbs:
      - get
      - patch
      - update
    - apiGroups:
      - ocs.openshift.io
      resources:
      - storageclusters
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - operators.coreos.com
      resources:
      - operatorgroups
      - subscriptions
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
      name: ibm-ocs-operator-leader-election-rolebinding
      namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ibm-ocs-operator-leader-election-role
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
      name: ibm-ocs-operator-manager-rolebinding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: ibm-ocs-operator-manager-role
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: kube-system
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
        name: ocs-controller
      name: ibm-ocs-operator-controller-manager
      namespace: kube-system
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ocs-controller
      template:
        metadata:
          labels:
            name: ocs-controller
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          containers:
          - args:
            - --enable-leader-election
            command:
            - /manager
            env:
            - name: CHANNEL
              value: stable-4.5
            - name: WATCH_NAMESPACE
              value: openshift-storage
            image: "icr.io/obs/ibm-ocs-operator:v0.0.13"
            imagePullPolicy: Always
            name: manager
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 200Mi
          terminationGracePeriodSeconds: 10
  - apiVersion: ocs.ibm.io/v1
    kind: OcsCluster
    metadata:
      name: {{ ocs-cluster-name }}
      namespace: default
      #labels:
      #    deploy.razee.io/Reconcile: false
    spec:
       monStorageClassName: "{{ mon-storage-class }}"
       monSize: "{{ mon-storage-size }}"
       osdStorageClassName: "{{ osd-storage-class }}"
       osdSize: "{{ osd-storage-size }}"
       monDevicePaths:
         {{#mon-device-path }}
         - "{{{ item }}}"
         {{/mon-device-path }}
       osdDevicePaths:
         {{#osd-device-path }}
         - "{{{ item }}}"
         {{/osd-device-path }}
       numOfOsd: {{ num-of-osd }}
       ocsUpgrade: {{ ocs-upgrade }}
       workerNodes:
         {{#worker-nodes}}
         - "{{{ item }}}"
         {{/worker-nodes}}
       billingType: "{{ billing-type }}"
       ibmCosAccessKey: "{{ibm-cos-access-key}}"
       ibmCosSecretKey: "{{ibm-cos-secret-key}}"
