apiVersion: v1
kind: List
metadata:
  name: netapp-trident-san
  namespace: kube-system
  annotations:
    version: 21.04
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: trident-kubectl-san
      namespace: "trident"
    spec:
      serviceAccountName: trident-kubectl-sa
      containers:
        - name: trident-kubectl-san
          image: icr.io/ibm/ibm-tridentctl:v2.0.1
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: "trident"
            - name: DRIVER_Name
              value: "ontap-san"
            - name: MGMT_LIF
              value: "{{{ managementLIF }}}"
            - name: DATA_LIF
              value: "{{{ dataLIF }}}"
            - name: SVM_Name
              value: "{{{ svm }}}"
            - name: USER_Name
              value: "{{{ username }}}"
            - name: USER_Password
              value: "{{{ password }}}"
            - name: LIMIT_VolumeSize
              value: "{{{ limitVolumeSize }}}"
            - name: LIMIT_AggregateUsage
              value: "{{{ limitAggregateUsage }}}"
